# GitHub Labels Configuration
# This file defines the labels used in the repository for better organization

labels:
  # Bug labels
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "bug:critical"
    color: "b60205"
    description: "Critical bug that needs immediate attention"
  - name: "bug:regression"
    color: "d73a4a"
    description: "Bug that was introduced in a recent change"

  # Enhancement labels
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "feature:request"
    color: "a2eeef"
    description: "User-requested feature"
  - name: "feature:improvement"
    color: "a2eeef"
    description: "Improvement to existing feature"

  # Documentation labels
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "docs:readme"
    color: "0075ca"
    description: "README updates"
  - name: "docs:api"
    color: "0075ca"
    description: "API documentation updates"

  # Help wanted labels
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"

  # Priority labels
  - name: "priority:high"
    color: "b60205"
    description: "High priority issue"
  - name: "priority:medium"
    color: "fbca04"
    description: "Medium priority issue"
  - name: "priority:low"
    color: "0e8a16"
    description: "Low priority issue"

  # Status labels
  - name: "status:needs-triage"
    color: "fbca04"
    description: "Issue needs to be reviewed and categorized"
  - name: "status:in-progress"
    color: "1d76db"
    description: "Work is in progress"
  - name: "status:blocked"
    color: "d93f0b"
    description: "Issue is blocked by something else"
  - name: "status:ready-for-review"
    color: "0e8a16"
    description: "Ready for review"

  # Type labels
  - name: "type:bug"
    color: "d73a4a"
    description: "Bug report"
  - name: "type:feature"
    color: "a2eeef"
    description: "Feature request"
  - name: "type:question"
    color: "d876e3"
    description: "Question or help request"
  - name: "type:security"
    color: "b60205"
    description: "Security-related issue"

  # Component labels
  - name: "component:bot"
    color: "1d76db"
    description: "Bot functionality"
  - name: "component:api"
    color: "1d76db"
    description: "API endpoints"
  - name: "component:database"
    color: "1d76db"
    description: "Database-related"
  - name: "component:docker"
    color: "1d76db"
    description: "Docker configuration"
  - name: "component:ci-cd"
    color: "1d76db"
    description: "CI/CD pipeline"

  # Template labels
  - name: "template:enhancement"
    color: "a2eeef"
    description: "Template improvement"
  - name: "template:documentation"
    color: "0075ca"
    description: "Template documentation"
  - name: "template:example"
    color: "7057ff"
    description: "Template example or sample"

  # Dependencies labels
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
  - name: "dependencies:security"
    color: "b60205"
    description: "Security-related dependency updates"
  - name: "dependencies:production"
    color: "0366d6"
    description: "Production dependency updates"
  - name: "dependencies:development"
    color: "0366d6"
    description: "Development dependency updates"

  # Version labels
  - name: "version:patch"
    color: "0e8a16"
    description: "Patch version bump"
  - name: "version:minor"
    color: "fbca04"
    description: "Minor version bump"
  - name: "version:major"
    color: "b60205"
    description: "Major version bump"

  # Won't fix labels
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "invalid"
    color: "e4e669"
    description: "Something is wrong"
